stages:
  - install
  - test

install_client:
  stage: install
  script:
    - cd client
    - npm install
    - npm run dev &
    - sleep 10
    - kill $!

install_server:
  stage: install
  script:
    - cd server
    - npm install
    - npm start &
    - sleep 10
    - kill $!

test_server:
  stage: test
  script:
    - cd server
    - npm test

test_client:
  stage: test
  script:
    - cd client
    - npm test
